name: re2 Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} - libre2 ABI version ${{ matrix.libre2.soname }} - Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - truffleruby-head
          - truffleruby-21.0.0
        libre2:
          - version: "20210202"
            soname: 9
        ubuntu:
          - '18.04'
          - '20.04'
        include:
          - ubuntu: '18.04'
            existing_libre2: 'libre2-4'
          - ubuntu: '20.04'
            existing_libre2: 'libre2-5'
    steps:
      - uses: actions/checkout@v2
      - name: Remove any existing libre2 installation
        run: sudo apt-get remove -y libre2-dev ${{ matrix.existing_libre2 }}
      - name: Download and install specific release of libre2
        run: |
          curl -Lo libre2-dev.deb https://github.com/mudge/re2-ci/releases/download/v1/libre2-dev_${{ matrix.libre2.version }}_${{ matrix.ubuntu }}_amd64.deb
          sudo dpkg -i libre2-dev.deb
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - run: bundle exec rake

  macos:
    name: Ruby ${{ matrix.ruby }} - macOS 10.15
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - truffleruby-head
          - truffleruby-21.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Install re2
        run: brew install re2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - run: bundle exec rake
